---
title: "COVID19 pandemic"
author: Kevin Leiss (https://twitter.com/kl_print)
date: 14.03.2020
output:
  html_document:
    df_print: paged
---
# Getting the data
```{r, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning = FALSE, message = FALSE)
```

Data was collected from [https://github.com/CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19).

```{r}
library(tidyverse)

cas = read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv") %>%
  gather("date", "cases", -c(`Province/State`,`Country/Region`, Lat, Long)) %>%
  mutate(date = as.Date(date, format = "%m/%d/%y")) %>%
  group_by(`Country/Region`, date) %>%
  summarise(cases = sum(cases))

recov = read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv") %>%
  gather("date", "recovered", -c(`Province/State`,`Country/Region`, Lat, Long)) %>%
  mutate(date = as.Date(date, format = "%m/%d/%y")) %>%
  group_by(`Country/Region`, date) %>%
  summarise(recovered = sum(recovered))

dea = read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv") %>%
  gather("date", "deaths", -c(`Province/State`,`Country/Region`, Lat, Long)) %>%
  mutate(date = as.Date(date, format = "%m/%d/%y")) %>%
  group_by(`Country/Region`, date) %>%
  summarise(deaths = sum(deaths))


df =  dr = left_join(cas, recov) %>%
  left_join(dea) %>%
  mutate(death_rate = deaths/cases) %>%
  mutate(death_rate = ifelse(is.nan(death_rate), 0, death_rate)) %>%
  mutate(still_infected = cases - recovered - deaths) %>%
  group_by(`Country/Region`) %>%
  filter(max(cases) > 500)

df = df %>%
  select(-death_rate) %>%
  gather("group", "n", -c(`Country/Region`, date)) %>%
  as_tibble()
```


# Countries with more than 500 cases:
The following shows the onset of the COVID19 pandemic in all countries which reported up to today at least 500 cases, starting from March 01, 2020.
```{r, dpi=300, fig.width=10, fig.height=7}
per.country <- df %>%
  group_by(`Country/Region`) %>%
  filter(date > "2020-03-01") %>%
  ggplot(aes(x = date, y = n, color=group, group = group)) +
  geom_line(size=.25) +
  facet_wrap(vars(`Country/Region`), scales = "free_y") +
  theme(axis.text.x = element_text(angle=90, hjust=1, vjust=.5)) +
  ggtitle("COVID19 cases") +
  labs(subtitle="Counties w/ > 500 cases, 01 Mar. 2020 onward
Source: https://github.com/CSSEGISandData/COVID-19") +
  ylab("cases")

per.country
```

And on log-scale:
```{r , dpi=300, fig.width=10, fig.height=7}
per.country + scale_y_log10() + ylab("log10(cases)")
```

